name: ${name}
version: ${version}
description: ${description}
author: ${author}
website: ${url}

main: ${mainClass}

commands:
  setspawn:
    description: "Sets the server spawn point using x,y,z,pitch,yaw."
    permission: globalspawn.setspawn
  spawn:
    description: "Teleports a player to the server spawn point."
    permission: globalspawn.spawn
  spawnreload:
    description: "Reloads configuration file."
    permission: globalspawn.spawnreload
permissions:
  globalspawn.*:
    children:
      globalspawn.setspawn: true
      globalspawn.spawn: true
      globalspawn.spawnreload: true
    description: "Gives access to all globalspawn commands"
  globalspawn.setspawn:
    default: op
    description: "Sets the server spawn point using x,y,z,pitch,yaw."
  globalspawn.spawn:
    default: true
    description: "Teleports a player to the server spawn point."
  globalspawn.spawnreload:
    default: op
    description: "Reloads configuration file."
